name: Build Application

on:
  push:
    branches:
      - main  # Adjust this if you want to build on a different branch
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # PyInstaller should be run in the target OS environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create credentials file
        run: |
          echo '${{ secrets.CREDENTIALS_FILE_CONTENT }}' > credentials.json
          echo '${{ secrets.GOOGLE_KEY }}' > ttsandtranslate-7dd2e2d80d42.json

      - name: Run PyInstaller
        run: |
          pyinstaller --add-data "*.json;." pyReadAloud.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pyReadAloud-windows
          path: dist/pyReadAloud.exe
